language: node_js
node_js:
  - "14.9.0"
before_install:
  -   openssl aes-256-cbc -K $encrypted_9e09dc4a4da7_key -iv $encrypted_9e09dc4a4da7_iv -in functions/serviceAccountKey.json.enc -out functions/serviceAccountKey.json -d
jobs:
  include:
    - stage: deploy to production
      script:
      - npm install -g firebase-tools
      - npm --prefix ./functions install
      - npm --prefix ./Front-End/everest install
      - npm --prefix ./Front-End/everest run build
      - cd functions
      - firebase emulators:exec --project impressive-hall-288310 --token $FIREBASE_TOKEN --only functions,firestore npm test
      deploy:
        skip_cleanup: true
        provider: firebase
        token: $FIREBASE_TOKEN
        on: 
          branch: master

  

