language: node_js
node_js:
  - "14.9.0"
script: 
  - echo "Deploying"
install:
  - npm install -g firebase-tools
  - npm --prefix ./functions install
  - npm --prefix ./Front-End/everest install
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  on: 
    branch: master
