language: node_js
node_js:
  - "14.9.0"
jobs:
  include:
    - stage: deploy to production
      script:
      - npm install -g firebase-tools
      - npm --prefix ./functions install
      - npm --prefix ./Front-End/everest install
      - npm --prefix ./Front-End/everest run build
      - npm test
      deploy:
        skip_cleanup: true
        provider: firebase
        token: $FIREBASE_TOKEN
        on: 
          branch: master

  

